import{a as P,S as q,i as C}from"./assets/vendor-BZXst8iV.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&t(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const E="20370935-71350e4ff636eebefea7dcc17",H="https://pixabay.com/api/",y=async(s,r=1,i=15)=>{const t=await P.get(H,{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:i}});return{hits:t.data.hits,totalHits:t.data.totalHits}};function L(s){return s.map(({webformatURL:r,largeImageURL:i,tags:t,likes:e,views:o,comments:l,downloads:S})=>`
        <li class="gallery-item" href="${i}">
          <div class="image-wrapper">
            <img src="${r}" alt="${t}" />
          </div>
          <div class="info">
            <p>Likes<br><strong>${e}</strong></p>
            <p>Views<br><strong>${o}</strong></p>
            <p>Comments<br><strong>${l}</strong></p>
            <p>Downloads<br><strong>${S}</strong></p>
          </div>
        </li>
      `).join("")}const g=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".loader"),c=document.querySelector(".load-more");let w=new q(".gallery li"),h=1;const d=15;let f="",a=new Set,u=0;const b=()=>m("error","Something went wrong. Please try again later!","#ff4d4d","fa fa-times-circle"),v=()=>m("info","We're sorry, but you've reached the end of search results.","#106BDA","fas fa-info-circle");function m(s,r,i,t){const e={message:r,position:"topRight",timeout:3e3,backgroundColor:i,titleColor:"#fff",messageColor:"#fff",icon:t,iconColor:"#fff",progressBarColor:"#fff",close:!0,closeOnClick:!0};C[s](e)}g.addEventListener("submit",async s=>{if(s.preventDefault(),f=g.elements.searchQuery.value.trim(),g.reset(),!f){m("warning","Enter a keyword to search!","#ffc107","fa fa-exclamation-circle");return}h=1,p.innerHTML="",a.clear(),c.classList.add("is-hidden"),n.classList.add("is-hidden"),n.classList.remove("is-hidden");try{const{hits:r,totalHits:i}=await y(f,h,d);u=i;const t=r.filter(e=>!a.has(e.id));if(t.forEach(e=>a.add(e.id)),t.length===0)m("error","Sorry, there are no images matching your search query. Please, try again!","#ff4d4d","fa fa-times-circle");else{const e=L(t);p.insertAdjacentHTML("beforeend",e),w.refresh(),a.size<u?c.classList.remove("is-hidden"):v()}}catch{b()}finally{n.classList.add("is-hidden")}});c.addEventListener("click",async()=>{n.classList.remove("is-hidden"),c.classList.add("is-hidden");let s=[],r=h+1;try{for(;s.length<d;){const{hits:i}=await y(f,r,d),t=i.filter(e=>!a.has(e.id));if(t.length===0||(t.forEach(e=>a.add(e.id)),s.push(...t),r+=1,a.size>=u))break}if(h=r-1,s.length>0){const i=L(s.slice(0,d));p.insertAdjacentHTML("beforeend",i),w.refresh();const t=document.querySelector(".gallery li");if(t){const e=t.getBoundingClientRect().height;window.scrollBy({top:e*3+20,behavior:"smooth"})}}a.size>=u||s.length<d?(c.classList.add("is-hidden"),n.classList.add("is-hidden"),v()):(c.classList.remove("is-hidden"),n.classList.add("is-hidden"))}catch{b()}finally{n.classList.add("is-hidden")}});
//# sourceMappingURL=index.js.map
