import{a as S,S as P,i as q}from"./assets/vendor-BZXst8iV.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const C="20370935-71350e4ff636eebefea7dcc17",E="https://pixabay.com/api/",L=async(r,t=1,i=9)=>{const s=await S.get(E,{params:{key:C,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:i}});return{hits:s.data.hits,totalHits:s.data.totalHits}};function w(r){return r.map(({webformatURL:t,largeImageURL:i,tags:s,likes:e,views:o,comments:d,downloads:v})=>`
        <li class="gallery-item" href="${i}">
  <div class="image-wrapper">
    <img src="${t}" alt="${s}" />
  </div>
  <div class="info">
              <p>Likes<br><strong>${e}</strong></p>
              <p>Views<br><strong>${o}</strong></p>
              <p>Comments<br><strong>${d}</strong></p>
              <p>Downloads<br><strong>${v}</strong></p>
            </div>
          </div>
        </li>
      `).join("")}const y=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".loader"),l=document.querySelector(".load-more"),f=document.querySelector(".load-complete");let b=new P(".gallery li"),m=1;const c=9;let h="",a=new Set,g=0;function u(r,t){const i={message:t,position:"topRight",timeout:2e3,backgroundColor:"#ff4d4d",titleColor:"#fff",messageColor:"#fff",icon:"fa fa-times-circle",iconColor:"#fff",progressBarColor:"#fff",close:!0,closeOnClick:!0};q[r](i)}y.addEventListener("submit",async r=>{if(r.preventDefault(),h=y.elements.searchQuery.value.trim(),!h){u("warning","Enter a keyword to search!");return}m=1,p.innerHTML="",a.clear(),l.classList.add("is-hidden"),f.classList.add("is-hidden"),n.classList.add("is-hidden"),n.classList.remove("is-hidden");try{const{hits:t,totalHits:i}=await L(h,m,c);g=i;const s=t.filter(e=>!a.has(e.id));if(s.forEach(e=>a.add(e.id)),s.length===0)u("error","Sorry, there are no images matching your search query. Please, try again!");else{const e=w(s);p.insertAdjacentHTML("beforeend",e),b.refresh(),a.size<g?l.classList.remove("is-hidden"):f.classList.remove("is-hidden")}}catch{u("error","Something went wrong. Please try again later!")}finally{n.classList.add("is-hidden")}});l.addEventListener("click",async()=>{n.classList.remove("is-hidden"),l.classList.add("is-hidden"),f.classList.add("is-hidden");let r=[],t=m+1;try{for(;r.length<c;){const{hits:i}=await L(h,t,c),s=i.filter(e=>!a.has(e.id));if(s.length===0||(s.forEach(e=>a.add(e.id)),r.push(...s),t+=1,a.size>=g))break}if(m=t-1,r.length>0){const i=w(r.slice(0,c));p.insertAdjacentHTML("beforeend",i),b.refresh()}a.size>=g||r.length<c?(l.classList.add("is-hidden"),n.classList.add("is-hidden"),f.classList.remove("is-hidden")):(l.classList.remove("is-hidden"),n.classList.add("is-hidden"),f.classList.add("is-hidden"))}catch{u("error","Something went wrong. Please try again later!")}finally{n.classList.add("is-hidden")}});
//# sourceMappingURL=index.js.map
